#!/bin/bash
. /mss/etc/funcs
rootcheck

bind_tmpdir="/tmp/bind"

print_usage(){
    aprint_usage "{iface} {post-up|pre-down}"
    aprint_usage "{named}"
    exit 1
}

handle_zone(){
    [ ! -d "${bind_tmpdir}" ] && mkdir "${bind_tmpdir}"

    case ${1} in
        self)
            echo "zone \".\" { type hint; file \"/var/named/zone/root-nov6\"; };" > "/tmp/bind/named.conf.local"

            [ "${2}" = "reload" ] && rndc reload
        ;;
        vpn)
            echo "zone \".\" { type forward; forwarders { ${2}; }; };" > "/tmp/bind/named.conf.local"
            rndc reload
        ;;
    esac
}

[ -z "${1}" ] && print_usage

case "${1}" in named)
    handle_zone self
    exit 0
    ;;
esac

wg_iface_list="$(wg show interfaces | sed 's/ /\n/g')"

iface_name="${1}"
iface_fwmark="$(wg show ${iface_name} fwmark | sed 's/^0x//')"
iface_allowed="$(wg show ${iface_name} allowed-ips | awk '{print $2}')"
iface_addr_nocidr="$(ip addr show ${iface_name} | awk '/inet/{sub(/\/[^.]*$/, ""); print $2}')"
iface_addr_dns="$(echo ${iface_addr_nocidr} | sed 's/\.[^.]*$//g').1"

case "${2}" in
    post-up)
        if [ ! "$(sysctl net.ipv4.conf.all.src_valid_mark | awk '{print $3}')" -eq 1 ]; then
            sysctl -q net.ipv4.conf.all.src_valid_mark=1
        fi

        if ! nft list table ip "wg-${iface_name}" >/dev/null 2>&1; then
            nft "add table ip wg-${iface_name}"
            nft "create chain ip wg-${iface_name} premangle {type filter hook prerouting priority mangle; policy accept;}"
            nft "create chain ip wg-${iface_name} postmangle {type filter hook postrouting priority mangle; policy accept;}"
            nft "add rule ip wg-${iface_name} premangle meta l4proto udp meta mark set ct mark"
            nft "add rule ip wg-${iface_name} postmangle meta l4proto udp meta mark 0x0000${iface_fwmark} ct mark set meta mark"
        fi

        case "${iface_allowed}" in
            0.0.0.0/0)
                nft "create chain ip wg-${iface_name} preraw {type filter hook prerouting priority raw; policy accept;}"
                nft "add rule ip wg-${iface_name} preraw iifname != \"${iface_name}\" ip daddr ${iface_addr_nocidr} fib saddr type != local drop"

                ip -4 route add "${iface_allowed}" dev "${iface_name}" table "0x${iface_fwmark}"
                ip -4 rule add pref "$((${iface_fwmark}))" table main suppress_prefixlength 0
                ip -4 rule add pref "$((${iface_fwmark}+1))" not fwmark "0x${iface_fwmark}" table "0x${iface_fwmark}"

                handle_zone vpn "${iface_addr_dns}"
            ;;
            *)
                ip -4 route add "${iface_allowed}" dev "${iface_name}"
                ip -4 rule add pref "${iface_fwmark}" fwmark "0x${iface_fwmark}" table main
            ;;
        esac
    ;;
    pre-down)
        if [ "$(echo "${wg_iface_list}" | grep -v ${iface_name} | wc -l)" -eq 0 ]; then
            sysctl -q net.ipv4.conf.all.src_valid_mark=0
        fi

        nft "delete table ip wg-${iface_name}"

        case "${iface_allowed}" in
            0.0.0.0/0)
                ip -4 rule del table main suppress_prefixlength 0
                ip -4 rule del not fwmark "0x${iface_fwmark}" table "0x${iface_fwmark}"

                handle_zone self reload
            ;;
            *)
                ip -4 rule del fwmark "0x${iface_fwmark}" table main
            ;;
        esac
    ;;
    *)
        print_usage
    ;;
esac
