#!/bin/sh
nfqwspid="$(pidof nfqws)"
iface="$(grep 00000000 /proc/net/route | awk 'NR==1 {print $1}')"

nfqws_iptb(){
 iptables -t mangle "-${1}" POSTROUTING \
  -p tcp -o "${2}"                         \
  -m multiport --dports 80,443             \
  -m connbytes --connbytes-dir=original    \
  --connbytes-mode=packets --connbytes 1:4 \
  -m mark ! --mark 0x40000000/0x40000000   \
  -j NFQUEUE --queue-num 200 --queue-bypass >/dev/null 2>&1
}

case "$1" in
 start)
  nfqws_iptb I "${iface}"

  nfqws \
   --uid=0:0                      \
   --qnum=200                     \
   --dpi-desync-fwmark=0x40000000 \
   --wssize=1:6                   \
   --hostcase                     \
   --hostspell=hoST               \
   --hostnospace                  \
   --domcase                      \
   --dpi-desync=fake              \
   --dpi-desync-fooling=md5sig    \
   --dpi-desync-retrans=1         \
   --dpi-desync-skip-nosni=0      \
   --dpi-desync-ttl=6 >/dev/null 2>&1 &
 ;;
 stop)
  nfqws_iptb D "${iface}"

  for i in ${nfqwspid}; do
   kill -TERM "${i}" || kill -KILL "${i}"
  done
 ;;
esac
